name: app_jht_front
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1 # Para el manejo de errores
  get_it: ^7.6.4 # Para la inyección de dependencias
  dio: ^5.3.3 # Cliente HTTP
  shared_preferences: ^2.2.2 # Para almacenamiento local simple
  equatable: ^2.0.5 # Para comparar objetos fácilmente
  freezed_annotation: ^2.4.1 # Para clases inmutables y data classes
  font_awesome_flutter: ^10.7.0 # Para los íconos (opcional)
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  intl: ^0.19.0
  url_launcher: ^6.2.4 
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  file_picker: ^8.0.0   # Para selección de imágenes

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  freezed: ^2.5.2
  flutter_launcher_icons: "^0.13.1" # <--- AGREGA ESTO
  mockito: ^5.4.4 # Para mocks en tests


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    # Declara toda la carpeta para que Flutter la reconozca
    - assets/images/ 
    # Si tienes íconos, puedes declararlos también:
    - assets/icons/ 


# pubspec.yaml (al final del archivo)

flutter_launcher_icons:
  android: "launcher_icon" # Nombre por defecto
  ios: true                # Generar para iOS
  image_path: "assets/icons/Jht.png" # <--- RUTA A TU IMAGEN PNG
  min_sdk_android: 21      # Mínimo recomendado
  remove_alpha_ios: true   # Opcional, si tu logo tiene transparencia y quieres un fondo de color